services:
  app:
    build: .
    container_name: my-node-app-container
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
 
  db:
   image: mysql:8.0
   container_name: practice-mysql
   restart: always
   environment:
    MYSQL_ROOT_PASSWORD: docker-practice
    MYSQL_DATABASE: docker-practice1
    MYSQL_USER: user1
    MYSQL_PASSWORD: user1pass
   ports:
     - "3306:3306"
   volumes:
     - ./mysql_data:/var/lib/mysql

